# Generated by Django 5.2.3 on 2025-07-07 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excelapp', '0006_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='id',
            field=models.CharField(auto_created=True, max_length=100, primary_key=True, serialize=False),
        ),
    ]
