# Generated by Django 5.2.3 on 2025-07-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excelapp', '0010_alter_employe_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
