# Generated by Django 5.2.3 on 2025-07-07 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excelapp', '0012_alter_employe_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='id',
            field=models.AutoField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
