# Generated by Django 5.2.3 on 2025-07-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excelapp', '0015_registrationform_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationform',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
