# Generated by Django 5.2.3 on 2025-07-10 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excelapp', '0016_alter_registrationform_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistrationForm',
        ),
    ]
