# Generated by Django 5.2.3 on 2025-07-10 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excelapp', '0018_registrationform'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='RegistrationForm',
        ),
    ]
